#!/bin/bash
install_dir="$1"
if [ ! -d $install_dir ]; then
  mkdir $install_dir
  module load python2/x86_64/2.7.2
  virtualenv -p python2.7 $install_dir --system-site-packages
  cd $install_dir
  source bin/activate
  pip install numpy matplotlib seaborn pandas sklearn GPy
  git clone https://github.com/mzwiessele/topslam
  mv topslam/topslam ../topslam
fi
